services:
  - type: web
    name: jurai-backend
    runtime: node
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        value: jurai_secret_key_2026
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: jurai-db
          property: connectionString
      - key: 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
        sync: false